spring.application.name=ai-database-analyst

spring.datasource.url=jdbc:postgresql://localhost:5432/ai_database_analyst
spring.datasource.username=postgres
spring.datasource.password=2303

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080